# Generated by Django 3.1.5 on 2021-01-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210129_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='creation_time',
            field=models.DateTimeField(),
        ),
    ]
