# Generated by Django 3.1.5 on 2021-02-01 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20210201_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 22, 18, 35, 446056)),
        ),
    ]
