# Generated by Django 3.1.5 on 2021-02-02 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_document_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 8, 26, 32, 841786)),
        ),
    ]
